apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}-mappings-configs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "wiremock.name" . }}
    helm.sh/chart: {{ include "wiremock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{.Values.configmap}}
{{/*{{- range $path, $bytes := .Files.Glob (printf "%s/*.json" "mappings")}}*/}}
{{/*    {{ $name := base $path }}*/}}
{{/*    {{- printf "%s" $name}}: {{ $.Files.Get $path |quote}}*/}}
{{/*  {{- end }}*/}}